SELECT * FROM HEALTH_DATA LIMIT 100;

----========================================================================
-- // 1. Univariate Analysis //

-- Unique number of hospital codes and their distribution
SELECT HOSPITAL_CODE, COUNT(*) AS CNT, COUNT(DISTINCT CASE_ID) AS CNT_CASES
FROM HEALTH_DATA
GROUP BY 1
ORDER BY 2 DESC;

-- Unique number of hospital type code and their distribution
SELECT HOSPITAL_TYPE_CODE, COUNT(DISTINCT HOSPITAL_CODE) AS CNT_HOSPITAL_CODE,COUNT(*) AS CNT, COUNT(DISTINCT CASE_ID) AS CNT_CASES
FROM HEALTH_DATA
GROUP BY 1
ORDER BY 2 DESC;

-- Unique number of city code hospital and their distribution
SELECT CITY_CODE_HOSPITAL, COUNT(DISTINCT HOSPITAL_CODE) AS CNT_HOSPITAL_CODE,
        COUNT(DISTINCT HOSPITAL_TYPE_CODE) AS CNT_HOSPITAL_TYPE_CODE,
        COUNT(*) AS CNT, COUNT(DISTINCT CASE_ID) AS CNT_CASES
FROM HEALTH_DATA
GROUP BY 1
ORDER BY 2 DESC;

-- Unique number of hospital region code and their distribution
SELECT HOSPITAL_REGION_CODE, COUNT(DISTINCT HOSPITAL_CODE) AS CNT_HOSPITAL_CODE,
        COUNT(DISTINCT HOSPITAL_TYPE_CODE) AS CNT_HOSPITAL_TYPE_CODE,
        COUNT(*) AS CNT, COUNT(DISTINCT CASE_ID) AS CNT_CASES
FROM HEALTH_DATA
GROUP BY 1
ORDER BY 2 DESC;

-- Unique number of department and their distribution
SELECT DEPARTMENT, COUNT(DISTINCT HOSPITAL_CODE) AS CNT_HOSPITAL_CODE,
        COUNT(DISTINCT HOSPITAL_TYPE_CODE) AS CNT_HOSPITAL_TYPE_CODE,
        COUNT(*) AS CNT, COUNT(DISTINCT CASE_ID) AS CNT_CASES
FROM HEALTH_DATA
GROUP BY 1
ORDER BY 2 DESC;

-- Unique number of Bed grade and their distribution
SELECT BED_GRADE, COUNT(DISTINCT HOSPITAL_CODE) AS CNT_HOSPITAL_CODE,
        COUNT(DISTINCT HOSPITAL_TYPE_CODE) AS CNT_HOSPITAL_TYPE_CODE,
        COUNT(*) AS CNT, COUNT(DISTINCT CASE_ID) AS CNT_CASES
FROM HEALTH_DATA
GROUP BY 1
ORDER BY 2 DESC;

-- Unique number of admission type and their distribution
SELECT TYPE_OF_ADMISSION, COUNT(DISTINCT HOSPITAL_CODE) AS CNT_HOSPITAL_CODE,
        COUNT(DISTINCT HOSPITAL_TYPE_CODE) AS CNT_HOSPITAL_TYPE_CODE,
        COUNT(*) AS CNT, COUNT(DISTINCT CASE_ID) AS CNT_CASES
FROM HEALTH_DATA
GROUP BY 1
ORDER BY 2 DESC;

-- Unique number of severity of illness and their distribution
SELECT SEVERITY_OF_ILLNESS, COUNT(DISTINCT HOSPITAL_CODE) AS CNT_HOSPITAL_CODE,
        COUNT(DISTINCT HOSPITAL_TYPE_CODE) AS CNT_HOSPITAL_TYPE_CODE,
        COUNT(*) AS CNT, COUNT(DISTINCT CASE_ID) AS CNT_CASES
FROM HEALTH_DATA
GROUP BY 1
ORDER BY 2 DESC;

-- Unique number of Age groups and their distribution
SELECT AGE, COUNT(DISTINCT HOSPITAL_CODE) AS CNT_HOSPITAL_CODE,
        COUNT(DISTINCT HOSPITAL_TYPE_CODE) AS CNT_HOSPITAL_TYPE_CODE,
        COUNT(*) AS CNT, COUNT(DISTINCT CASE_ID) AS CNT_CASES
FROM HEALTH_DATA
GROUP BY 1
ORDER BY 2 DESC;
----========================================================================

-- // 2/3/4. Does patient length of stay (LOS) change wrt HOSPITAL_TYPE_CODE/CITY_CODE_HOSPITAL/HOSPITAL_REGION_CODE? //

SELECT HOSPITAL_TYPE_CODE, 
        MIN(DATEDIFF(day,ADMISSION_DATE,DISCHARGE_DATE)) AS MIN_LOS,
        MAX(DATEDIFF(day,ADMISSION_DATE,DISCHARGE_DATE)) AS MAX_LOS,
        AVG(DATEDIFF(day,ADMISSION_DATE,DISCHARGE_DATE)) AS AVG_LOS,
        MEDIAN(DATEDIFF(day,ADMISSION_DATE,DISCHARGE_DATE)) AS MEDIAN_LOS
FROM HEALTH_DATA 
GROUP BY 1;
-- Feedback: Hospital type code 'g' has significantly highest LOS 

SELECT CITY_CODE_HOSPITAL, 
        MIN(DATEDIFF(day,ADMISSION_DATE,DISCHARGE_DATE)) AS MIN_LOS,
        MAX(DATEDIFF(day,ADMISSION_DATE,DISCHARGE_DATE)) AS MAX_LOS,
        AVG(DATEDIFF(day,ADMISSION_DATE,DISCHARGE_DATE)) AS AVG_LOS,
        MEDIAN(DATEDIFF(day,ADMISSION_DATE,DISCHARGE_DATE)) AS MEDIAN_LOS
FROM HEALTH_DATA 
GROUP BY 1;
-- Feedback: No significant observations

SELECT HOSPITAL_REGION_CODE, 
        MIN(DATEDIFF(day,ADMISSION_DATE,DISCHARGE_DATE)) AS MIN_LOS,
        MAX(DATEDIFF(day,ADMISSION_DATE,DISCHARGE_DATE)) AS MAX_LOS,
        AVG(DATEDIFF(day,ADMISSION_DATE,DISCHARGE_DATE)) AS AVG_LOS,
        MEDIAN(DATEDIFF(day,ADMISSION_DATE,DISCHARGE_DATE)) AS MEDIAN_LOS
FROM HEALTH_DATA 
GROUP BY 1;
-- Feedback: No significant observations
----========================================================================

-- // 5. DEPARTMENT of admission and its impact on LOS //

SELECT DEPARTMENT, 
        MIN(DATEDIFF(day,ADMISSION_DATE,DISCHARGE_DATE)) AS MIN_LOS,
        MAX(DATEDIFF(day,ADMISSION_DATE,DISCHARGE_DATE)) AS MAX_LOS,
        AVG(DATEDIFF(day,ADMISSION_DATE,DISCHARGE_DATE)) AS AVG_LOS,
        MEDIAN(DATEDIFF(day,ADMISSION_DATE,DISCHARGE_DATE)) AS MEDIAN_LOS
FROM HEALTH_DATA 
GROUP BY 1;
-- Feedback: Surgeries have higher LOS, Anesthesia cases have lower LOS.
----========================================================================

-- // 6. DEPARTMENT X HOSPITAL_REGION_CODE and its impact on LOS //
SELECT DEPARTMENT, HOSPITAL_REGION_CODE, 
        MIN(DATEDIFF(day,ADMISSION_DATE,DISCHARGE_DATE)) AS MIN_LOS,
        MAX(DATEDIFF(day,ADMISSION_DATE,DISCHARGE_DATE)) AS MAX_LOS,
        AVG(DATEDIFF(day,ADMISSION_DATE,DISCHARGE_DATE)) AS AVG_LOS,
        MEDIAN(DATEDIFF(day,ADMISSION_DATE,DISCHARGE_DATE)) AS MEDIAN_LOS
FROM HEALTH_DATA 
GROUP BY 1,2;
-- Feedback: surgery's higher LOS are not affected by Hospital Region Code
----========================================================================

-- // 7. Does more AVAILABLE_EXTRA_ROOMS_IN_HOSPITAL impact a patients LOS // (Insight)

SELECT AVAILABLE_EXTRA_ROOMS_IN_HOSPITAL,
        MIN(DATEDIFF(day,ADMISSION_DATE,DISCHARGE_DATE)) AS MIN_LOS,
        MAX(DATEDIFF(day,ADMISSION_DATE,DISCHARGE_DATE)) AS MAX_LOS,
        AVG(DATEDIFF(day,ADMISSION_DATE,DISCHARGE_DATE)) AS AVG_LOS,
        MEDIAN(DATEDIFF(day,ADMISSION_DATE,DISCHARGE_DATE)) AS MEDIAN_LOS,
        COUNT(DISTINCT CASE_ID) AS CNT_CASES
FROM HEALTH_DATA 
GROUP BY 1;
-- Feedback: Admissions when lesser extra rooms in hospital resulted in higher LOS
----========================================================================

-- // 8. TYPE_OF_ADMISSION and its impact on LOS // (Insight)

SELECT TYPE_OF_ADMISSION,
        MIN(DATEDIFF(day,ADMISSION_DATE,DISCHARGE_DATE)) AS MIN_LOS,
        MAX(DATEDIFF(day,ADMISSION_DATE,DISCHARGE_DATE)) AS MAX_LOS,
        AVG(DATEDIFF(day,ADMISSION_DATE,DISCHARGE_DATE)) AS AVG_LOS,
        MEDIAN(DATEDIFF(day,ADMISSION_DATE,DISCHARGE_DATE)) AS MEDIAN_LOS,
        COUNT(DISTINCT CASE_ID) AS CNT_CASES
FROM HEALTH_DATA 
GROUP BY 1;
-- Feedback: Trauma has higher LOS
----========================================================================

-- // 9. SEVERITY_OF_ILLNESS and its impact on LOS // (Insight)

SELECT SEVERITY_OF_ILLNESS,
        MIN(DATEDIFF(day,ADMISSION_DATE,DISCHARGE_DATE)) AS MIN_LOS,
        MAX(DATEDIFF(day,ADMISSION_DATE,DISCHARGE_DATE)) AS MAX_LOS,
        AVG(DATEDIFF(day,ADMISSION_DATE,DISCHARGE_DATE)) AS AVG_LOS,
        MEDIAN(DATEDIFF(day,ADMISSION_DATE,DISCHARGE_DATE)) AS MEDIAN_LOS,
        COUNT(DISTINCT CASE_ID) AS CNT_CASES
FROM HEALTH_DATA 
GROUP BY 1;
-- Feedback: Extreme illness resulted in higher LOS
----========================================================================

-- // 10. AGE and its impact on LOS // (Insight)

SELECT AGE,
        MIN(DATEDIFF(day,ADMISSION_DATE,DISCHARGE_DATE)) AS MIN_LOS,
        MAX(DATEDIFF(day,ADMISSION_DATE,DISCHARGE_DATE)) AS MAX_LOS,
        AVG(DATEDIFF(day,ADMISSION_DATE,DISCHARGE_DATE)) AS AVG_LOS,
        MEDIAN(DATEDIFF(day,ADMISSION_DATE,DISCHARGE_DATE)) AS MEDIAN_LOS,
        COUNT(DISTINCT CASE_ID) AS CNT_CASES
FROM HEALTH_DATA 
GROUP BY 1;
-- Feedback: LOS increases as age increases
----========================================================================

-- // 11. ADMISSION_DEPOSIT and its relation to LOS //

SELECT DISTINCT ADMISSION_DEPOSIT FROM HEALTH_DATA; --- Ranges from 1800 to 11000

WITH BASE AS (
    SELECT ADMISSION_DEPOSIT,
            CASE WHEN ADMISSION_DEPOSIT <= 3000 THEN '1. Less than 3K'
                 WHEN ADMISSION_DEPOSIT > 7000 THEN '3. Greater than 7K'   
            ELSE '2. Between 3K to 7K' END AS DEPOSIT_BUCKET,
            ADMISSION_DATE,
            DISCHARGE_DATE,
            CASE_ID
    FROM HEALTH_DATA
)

-- SELECT * FROM BASE;

SELECT DEPOSIT_BUCKET,
        MIN(DATEDIFF(day,ADMISSION_DATE,DISCHARGE_DATE)) AS MIN_LOS,
        MAX(DATEDIFF(day,ADMISSION_DATE,DISCHARGE_DATE)) AS MAX_LOS,
        AVG(DATEDIFF(day,ADMISSION_DATE,DISCHARGE_DATE)) AS AVG_LOS,
        MEDIAN(DATEDIFF(day,ADMISSION_DATE,DISCHARGE_DATE)) AS MEDIAN_LOS,
        COUNT(DISTINCT CASE_ID) AS CNT_CASES
FROM BASE
GROUP BY 1
ORDER BY 1;
-- Feedback: No significant insight but LOS is increasing as the deposit increases
----========================================================================

-- // 12. Does more visitors come with patients who have more severe illness? //

SELECT SEVERITY_OF_ILLNESS,
        COUNT(DISTINCT CASE_ID) AS CNT_CASES,
        MIN(VISITORS_WITH_PATIENT) AS MIN_VISITORS,
        MAX(VISITORS_WITH_PATIENT) AS MAX_VISITORS,
        AVG(VISITORS_WITH_PATIENT) AS AVG_VISITORS,
        MEDIAN(VISITORS_WITH_PATIENT) AS MEDIAN_VISITORS
FROM HEALTH_DATA 
GROUP BY 1;
-- Feedback: No significant insight, but people with extreme illness have slightly more number of visitors

----========================================================================
-- // 13. Is there any differences in the LOS for different WARD_TYPE & WARD_FACILITY_CODE in each DEPARTMENT // (Insight)

SELECT DEPARTMENT,WARD_TYPE,WARD_FACILITY_CODE,
        COUNT(DISTINCT CASE_ID) AS CNT_CASES,
        MIN(DATEDIFF(day,ADMISSION_DATE,DISCHARGE_DATE)) AS MIN_LOS,
        MAX(DATEDIFF(day,ADMISSION_DATE,DISCHARGE_DATE)) AS MAX_LOS,
        AVG(DATEDIFF(day,ADMISSION_DATE,DISCHARGE_DATE)) AS AVG_LOS,
        MEDIAN(DATEDIFF(day,ADMISSION_DATE,DISCHARGE_DATE)) AS MEDIAN_LOS
FROM HEALTH_DATA 
GROUP BY 1,2,3
ORDER BY 1,2,3;
-- Feedback: LOS significantly changes as the combination of department, ward_type and facility_code varies

SELECT DEPARTMENT, SEVERITY_OF_ILLNESS,
        COUNT(DISTINCT CASE_ID) AS CNT_CASES,
        MIN(DATEDIFF(day,ADMISSION_DATE,DISCHARGE_DATE)) AS MIN_LOS,
        MAX(DATEDIFF(day,ADMISSION_DATE,DISCHARGE_DATE)) AS MAX_LOS,
        AVG(DATEDIFF(day,ADMISSION_DATE,DISCHARGE_DATE)) AS AVG_LOS,
        MEDIAN(DATEDIFF(day,ADMISSION_DATE,DISCHARGE_DATE)) AS MEDIAN_LOS
FROM HEALTH_DATA 
GROUP BY 1,2
ORDER BY 1,2;
-- Feedback: Surgery with Extreme illness have higher LOS and Anesthesia with Minon illness has lower LOS
----========================================================================

-- // 14. Does BED_GRADE affects LOS of patients? // (Insight)

SELECT BED_GRADE,
        COUNT(DISTINCT CASE_ID) AS CNT_CASES,
        MIN(DATEDIFF(day,ADMISSION_DATE,DISCHARGE_DATE)) AS MIN_LOS,
        MAX(DATEDIFF(day,ADMISSION_DATE,DISCHARGE_DATE)) AS MAX_LOS,
        AVG(DATEDIFF(day,ADMISSION_DATE,DISCHARGE_DATE)) AS AVG_LOS,
        MEDIAN(DATEDIFF(day,ADMISSION_DATE,DISCHARGE_DATE)) AS MEDIAN_LOS
FROM HEALTH_DATA 
GROUP BY 1;
-- Feedback: No significant insights

SELECT SEVERITY_OF_ILLNESS,BED_GRADE,
        COUNT(DISTINCT CASE_ID) AS CNT_CASES,
        MIN(DATEDIFF(day,ADMISSION_DATE,DISCHARGE_DATE)) AS MIN_LOS,
        MAX(DATEDIFF(day,ADMISSION_DATE,DISCHARGE_DATE)) AS MAX_LOS,
        AVG(DATEDIFF(day,ADMISSION_DATE,DISCHARGE_DATE)) AS AVG_LOS,
        MEDIAN(DATEDIFF(day,ADMISSION_DATE,DISCHARGE_DATE)) AS MEDIAN_LOS
FROM HEALTH_DATA 
GROUP BY 1,2
ORDER BY 1,2;
-- Feedback: No significant insights
----========================================================================

-- // 15. Do more visitors come when younger patients got admitted than older patients? // (Insight)
SELECT AGE,
        COUNT(DISTINCT CASE_ID) AS CNT_CASES,
        MIN(VISITORS_WITH_PATIENT) AS MIN_VISITORS,
        MAX(VISITORS_WITH_PATIENT) AS MAX_VISITORS,
        AVG(VISITORS_WITH_PATIENT) AS AVG_VISITORS,
        MEDIAN(VISITORS_WITH_PATIENT) AS MEDIAN_VISITORS
FROM HEALTH_DATA 
GROUP BY 1
ORDER BY 1;
-- Feedback: No significant insights (Childhood or Old age cases have a higher number of visitors)
----========================================================================


